version: '3.4'

services:
  api:
    container_name: "rateservice"
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/go/src/github.com/mannanmcc/rateservice
    ports:
      - 50051:50051
    tty: true
    restart: on-failure
    environment:
      CONFIG_FILE: "/go/src/github.com/mannanmcc/rateservice/config.yaml"
     